version: 2

jobs:
  test:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.14.4
      - image: amazon/dynamodb-local

    working_directory: /go/src/github.com/d-tsuji/sample-circleci

    # Environment values for all container
    environment:
      - GO111MODULE: "on"
        REVIEWDOG_GITHUB_API_TOKEN:
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Install GolangCI-Lint
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.27.0
      - run:
          command: |
            go get -u golang.org/x/lint/golint
          name: Install Golint
      - run:
          command: |
            go get -u github.com/reviewdog/reviewdog/cmd/reviewdog
          name: Install reviewdog
      - run:
          name: Fetch dependencies
          command: go mod download
      - run:
          name: Wait for DynamoDB
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 8000 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for DyanmoDB Local && exit 1
      - run:
          name: Run all unit tests
          command: |
            export AWS_REGION=ap-northeast-1
            export AWS_ACCESS_KEY_ID=dummy
            export AWS_SECRET_ACCESS_KEY=dummy
            export DYNAMO_ENDPOINT=http://localhost:8000
            export DYNAMO_TABLE_USER=local_user
            make test
      - run:
          name: Execute reviewdog
          command: |
            if [ -n "$CI_PULL_REQUEST" ]; then
              golint $(go list ./...) | reviewdog -name=golint -reporter='github-pr-review'
              golangci-lint run --out-format checkstyle | reviewdog -name=golangci-lint -f=checkstyle -reporter='github-pr-review'
            fi
          environment:
              REVIEWDOG_GITHUB_API_TOKEN: $REVIEWDOG_GITHUB_API_TOKEN

workflows:
  version: 2
  build-and-test:
    jobs:
      - test
